### PR TITLE
Update the bundled Node version to v12.4.0

### PR DESCRIPTION
**Pull request by DeeDeeG**
### Description of the Change

Update bundled Node to v12.4.0, which matches [the version in Electron 6](https://www.electronjs.org/releases/stable?version=6&page=6).

### Alternate Designs

None. We intend to match the Node version in `apm` to that which the version of Electron we use in Atom is based on.

Our Atom is using Electron 6. So we should bundle Node v12.4.0 in `apm`.

### Benefits

For packages that try to detect the version of Node they are building against during install, this closely approximates the version of Node used in Atom's version of Electron. So if there are any potential bugs in various packages due to non-matching versions of Node/Electron, this should take care of 99% of them, maybe even all of them.

### Possible Drawbacks

None expected. This is just a minor version update of Node.

### Verification Process

CI and manual testing, to be done soon.

### Applicable Issues

For a discussion of the type of issue this is designed to address, see: https://github.com/atom/apm/issues/328

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Thanks for merging the other PRs. 

I've indicated this elsewhere, but as a reminder: I am hoping there is a release with Node  v12.0.0, and then this is for the next release after that (one minor release per Node version bump I guess).

Not that we can't do that right away if you want. Just that I'd like there to be an earlier release with Node v12.0.0.

**Comment by DeeDeeG** [comment]
We do not have to bump dependencies or do any of the other to-dos I put before making a release (`apm` v2.7.0?) with Node v12.4.0.

I was thinking of e.g. bumping `tar` to v4 to match/dedupe with the version used by `npm`. And some things like that. The big "get rid of `fs-plus`" PR at upstream appears to  need more work regarding `try/catch` blocks, so I won't be looking to merge it here soon while it's active at upstream. But none of this is super critical, and I can get to those things for later releases if need be.

**Comment by aminya** [comment]
Please rebase

**Comment by DeeDeeG** [comment]
@aminya rebased. Thanks.

**Pull request merged**
