### PR TITLE
Update bundled Node to v12, which matches Atom's Electron 5

### PR DESCRIPTION
**Pull request by DeeDeeG**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

- Update `keytar` to a version that builds on Node v12.
- Update Node to v12.0.0 to match [upstream] Atom (which has Electron 5.0.13 --> Node 12.0.0).

<details><summary>Nitty-gritty details (click to expand):</summary>

- Atom has Electron 5.0.13
  - https://github.com/atom/atom/pull/20172 (PR is titled incorrectly. It's 5.0._13_, not _12_.)
  - See: ["electronVersion" in `package.json`](https://github.com/atom/atom/blob/02aa6b1c250d54a7a00a74a9592ce466d42afe5f/package.json#L15)
- Electron 5.x has Node 12.0.0, sort of.
  - Changelog entry for Electron 5.0.0 mentions Node 12.0.0: https://www.electronjs.org/releases/stable?version=5&page=3#5.0.0 
  - See: ['node_version' in DEPS at the electron repo](https://github.com/electron/electron/blob/5-0-x/DEPS#L14-L15)
    - [The Node commit Electron 5.x uses](https://github.com/nodejs/node/commit/666c67e078bddc32f25409f4a929c1e9b5f47373) is "approximately Node 12", but a couple hundred commits behind the actual stable [`v12.0.0` tag](https://github.com/nodejs/node/tree/v12.0.0) at `github.com/nodejs/node`???
      - Mentioned here by electron maintainers: https://github.com/electron/electron/pull/19292#discussion_r304142155
      - Comparison of `666c67e` to `v12.0.0` at nodejs/node: https://github.com/nodejs/node/compare/666c67e078bddc32f25409f4a929c1e9b5f47373...v12.0.0

Latest Atom nightly reports Node v12.0.0:

```console
$ atom-nightly  --version
Atom    : 1.49.0-nightly0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

</details>

### Alternate Designs

- Try to get Atom to update to a newer version of Electron (they are kind of overdue).
  - We would still be updating to some Node v12.x release. Just a somewhat newer minor/patch.
    - Which Node is used by which Electron? See: https://www.electronjs.org/docs/tutorial/electron-timelines

Or

- YOLO: use some newer version of Node v12.x that doesn't strictly match Atom.

Node major versions are meant to be fairly stable, so in theory we can use any version of Node v12.x (not just strictly the first release in the series, v12.0.0). But this is already an area where the failures are obscure/hard to track down. The more we differ here from the node that will run Atom packages, the wider the opening for behavior differences --> bugs. So to err on the safe side, we can match Electron as closely as possible. I just went with Node v12.0.0 to match Atom/Electron as closely as possible.

### Benefits

Should handle some certain cases where Atom packages/their dependencies (various node modules) need to be built and run on the same version of Node. For example: `node-sass` as discussed in https://github.com/atom/apm/issues/328.

### Possible Drawbacks

As always, major version bumps are a thing to watch for breakages.

While this is newer than the Node we had for a while, v10.2.1, it is older than what we just upgraded to last, v10.20.1. Any bugs fixed in Node 12.x in the past year aren't included in this. (Probably just another reason to bug the Atom team to update to newer Electron, IMO.)

- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.0.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.2.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.20.1

### Verification Process

I ran the following: `./bin/npm test` and `./bin/apm install tree-view`. CI should pass.

### Applicable Issues

Upstream PR: https://github.com/atom/apm/pull/889

See [past](https://github.com/atom/apm/pull/831) [node](https://github.com/atom/apm/pull/796) [upgrades](https://github.com/atom/apm/pull/694) [in [the upstream] repo](https://github.com/atom/apm/pull/563) for relevant discussion.

### CODE REVIEW

**Comment by aminya** [comment]
When creating PRs try to be compact. You can remove the initial `requirements` thing for example.

**Comment by DeeDeeG** [comment]
I copy-pasted this from the upstream PR. I wasn't trying to spend time editing the PR body a lot.

**Comment by DeeDeeG** [comment]
If we are dead set on compact PR bodies we should edit the template at our repo to not include the requirements.

**Comment by aminya** [comment]
We should update the templates. GitHub supports multiple templates, but currently, they use some external links for storing them!

**Comment by DeeDeeG** [comment]
I am comfortable simply deleting the "requirements" each time. That takes much less time than hiding them in `<details></details>` HTML tags. Not sure I want to edit the templates in this repo, on second thought.

**Pull request merged**
