### PR TITLE
deps: Bump tar to v6

### PR DESCRIPTION
**Pull request by DeeDeeG**
### Description of the Change

Bumps tar to v6. Required a slight change to invoking tar (`tar.Extract` --> `tar.extract`, option `path:` --> option `cwd:`).

### Alternate Designs

- Stay on outdated `tar` (I can't see a reason to do that)

### Benefits

This is supposedly faster, according to [the CHANGELOG](https://github.com/npm/node-tar/blob/master/CHANGELOG.md#30).

It's only used in a couple of places, though: When installing `apm` (should extract the bundled Node a bit faster), and whenever `apm/lib/package-converter.js` is used (appears to only be used when running `apm init`) [[1](https://github.com/atom-ide-community/apm/blob/6777ef6db0c1dda9983c47c4d89c7572569dc966/src/package-converter.coffee#L9)] [[2](https://github.com/atom-ide-community/apm/blob/6777ef6db0c1dda9983c47c4d89c7572569dc966/src/init.coffee#L84)].

This is the version of tar used in npm 7 (currently still in beta). Maybe some day we will be able to dedupe this dependency with npm@7? (Not extremely important, though.)

### Possible Drawbacks

None expected. npm 7 beta has been using this version of tar already.

### Verification Process

CI should pass.

### Applicable Issues

See the experimental PR attempting to bump all the dependencies. This checks one dependency off the list. https://github.com/atom-ide-community/apm/pull/19

### CODE REVIEW

**Comment by DeeDeeG** [comment]
@aminya please take a look.

This gives us a newer dependency that should be faster than before. It's in sync with `npm`'s dependency for the same module, so it gets deduped during install, which is nice.

**Comment by DeeDeeG** [comment]
I'm pretty sure the failing AppVeyor build is not related to this PR.

(It errored out before it even began installing dependencies. And only during one run. The rest of the runs passed.)

**Comment by DeeDeeG** [comment]
I'll say this ahead of time: if you'd rather have tar v6, then go for it. Just make sure CI passes.

(And if we do that we should change the PR title so the merge commit doesn't say "v4" when we're actually merging tar v6.)

**Comment by aminya** [comment]
Could you go to the latest version?

**Comment by DeeDeeG** [comment]
Yes, I can do tar@6. (I found out npm@7 (the next version, currently in beta) will have tar@6. Just  saw you edited your comment to say the same thing. So we'll be synced with npm again... eventually. It's not a heavy dependency anyway, I think.)

Did you see my comment in #19? I was able to upgrade all dependencies other than colors, async, and yargs to their latest versions and CI passes.

It might be smarter to do them one at a time I guess, rathe rthan all at once. But it seems pretty doable to upgrade almost everything at some point if we want.

**Comment by DeeDeeG** [comment]
It's updated to tar v6.

CI is passing on GitHub Actions. AppVeyor is taking a while as always.

**Review by aminya — APPROVED** [review]
Thank you

**Comment by aminya** [comment]
Please upstream this.

**Pull request merged**
