### PR TITLE
Downgrade coffeelint to 1

### PR DESCRIPTION
**Pull request by aminya**
This is a patch for #36.

### CODE REVIEW

**Comment by DeeDeeG** [comment]
I found out something unexpected: Upstream is compiling with coffeescript 2.3.2.

After #36 our fork is compiling with coffeescript 2.5.1.

**Comment by aminya** [comment]
That's because of intervening npm's normal operation by calling rebuild, dedup, etc a bunch of times, which causes the dependencies to shamefully hoist. These are very toxic and we should get rid of them.

**Comment by DeeDeeG** [comment]
Well, upstream was using coffeescript 2.x due to their grunt coffeescript plugin.

**Comment by aminya** [comment]
Probably they did not notice that grunt-contrib shamefully hoists coffeescirpt and overrides the explicit coffee-script.

**Comment by DeeDeeG** [comment]
I agree `npm dedupe` in the postinstall script is not needed with modern `npm`. I would like us to remove that from `script/postinstall`.

**Comment by DeeDeeG** [comment]
Yeah, their `coffee-script` devDependency does nothing, I'm pretty sure. But it's nice to be on newer coffeescript, soI'm not complaining.

`apm` was written and re-written many times over when it was new. And not entirely cleaned up well afterward. That's how I see it.

**Comment by aminya** [comment]
coffeescript 2 is not supported by Atom because of its breaking changes. Atom ships CoffeeScript 1 for compatibility and converted most of the things to JavaScript.

Using CoffeeScript 1 was a mistake by the developers at the time.

**Comment by DeeDeeG** [comment]
In production, apm compiles its own code to javascript in the `lib/` directory. After that, it runs as javascript. It shouldn't matter what Atom supports or doesn't support.

apm has been working this whole time compiling with coffeescript 2.x.  So I think it's perfectly safe to keep using coffeescript 2.x.

**Pull request merged**
