### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by aminya**
### Description of the Change

This bumps the dependencies of apm.

### Benefits

Using the last dependencies ensures the latest performance, functionality, and security improvements

### Verification
All the tests pass in CI and locally.

### CODE REVIEW

**Comment by DeeDeeG** [comment]
If I recall correctly, a few dependency upgrades to latest _do_ break the tests. `colors` is one of them. Also I believe `tar.Extract()` needs to be replaced with `tar.extract()` or `tar.x` as of the `tar@3` major version bump. but I forget the rest at the moment.

Rather than fully updating them to latest, if there are any dependencies that `npm` also uses, we can sync with `npm` and the dependency will be deduped, so the built Atom is slightly lighter I guess. that was what I had in mind to do next for dependencies: sync them with npm.

**Comment by DeeDeeG** [comment]
I merged this fork's `master` into an old branch where I maximally upgraded everything possible:

Take a look if you like. [CI is passing](https://github.com/DeeDeeG/apm/runs/1063202620). I'm not sure upgrading everything like that is actually a good idea, especially the `devDependencies`, but it seems like it should work.

https://github.com/DeeDeeG/apm/compare/update-dependencies-atomic

**Comment by aminya** [comment]
> Rather than fully updating them to latest, if there are any dependencies that `npm` also uses, we can sync with `npm` and the dependency will be deduped, so the built Atom is slightly lighter I guess. 

Apm runs in an external node process. There is no benefit in using the same versions as npm. 

If you want to make apm load faster, you should build it using Parcel to tree-shake the dependencies properly.

**Comment by aminya** [comment]
The tests don't run correctly after this. I need to debug the issue

**Comment by DeeDeeG** [comment]
> Apm runs in an external node process. There is no benefit in using the same versions as npm.

I meant that since apm is a wrapper around npm, if we use the same dependencies that apm's internal copy of npm uses under the hood, we can dedupe.

> The tests don't run correctly after this. I reverted this. We need to bump one by one until the issue shows itself.

You can investigate for yourself, but spoiler alert: I know the answer. `colors`, `async` and `yargs` have breaking changes such as a changed API. Everything but those three can be updated to the latest version, no problems. Or at least the tests will pass.

**Pull request merged**
